# Generated by Django 5.2.6 on 2025-10-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Código único del módulo (ej: 'inventarios')", unique=True)),
                ('name', models.CharField(help_text="Nombre descriptivo del módulo (ej: 'Inventarios')", max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icono para el menú (opcional)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descripción del módulo')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización en el menú')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Descripción del rol')),
                ('group', models.OneToOneField(help_text='Grupo de Django asociado al rol', on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, help_text='Puede ver/listar registros')),
                ('can_add', models.BooleanField(default=False, help_text='Puede agregar nuevos registros')),
                ('can_change', models.BooleanField(default=False, help_text='Puede modificar registros existentes')),
                ('can_delete', models.BooleanField(default=False, help_text='Puede eliminar registros')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_perms', to='accounts.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_perms', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulos',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
