# Generated by Django 5.2.5 on 2025-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('compras', 'Operador de Compras'), ('inventario', 'Operador de Inventario'), ('produccion', 'Operador de Producción'), ('ventas', 'Operador de Ventas'), ('finanzas', 'Analista Financiero')], max_length=50),
        ),
    ]
