# Generated by Django 5.2.5 on 2025-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListarPrecios',
            fields=[
                ('idlistarprecios', models.AutoField(db_column='idListarPrecios', primary_key=True, serialize=False)),
                ('canal', models.CharField(blank=True, db_column='Canal', max_length=50, null=True)),
                ('temporada', models.CharField(blank=True, db_column='Temporada', max_length=45, null=True)),
                ('valor', models.IntegerField(blank=True, db_column='Valor', null=True)),
            ],
            options={
                'db_table': 'listarprecios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PedidoDeVenta',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
        migrations.AlterModelTable(
            name='bodega',
            table='bodega',
        ),
        migrations.AlterModelTable(
            name='costo',
            table='costo',
        ),
        migrations.AlterModelTable(
            name='movimientoinventario',
            table='movimientoinventario',
        ),
        migrations.AlterModelTable(
            name='ordendecompra',
            table='ordendecompra',
        ),
        migrations.AlterModelTable(
            name='ordenproduccion',
            table='ordenproduccion',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
