# Generated by Django 5.2.5 on 2025-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_cliente_listarprecios_pedido_delete_pedidodeventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('idProducto_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Producto_Proveedor',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
