# Generated by Django 5.2.5 on 2025-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_remove_perfilusuario_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idbodega', models.AutoField(db_column='idBodega', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('idcosto', models.AutoField(db_column='idCosto', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Costo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('idmovimientoinventario', models.AutoField(db_column='idMovimientoInventario', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'MovimientoInventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('monto_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordendeCompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'OrdenProduccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoDeVenta',
            fields=[
                ('id_pedido_de_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('monto_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pedido_de_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.AutoField(db_column='idReceta', primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('insumos_necesarios', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('monto_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitudCompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('permisos', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
