# Generated by Django 5.2.7 on 2025-11-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_categoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
