# Generated by Django 5.2.6 on 2025-11-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_alter_producto_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
